# Generated by Django 5.1.3 on 2024-11-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_certification_alter_category_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='certification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='recertification_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
