# Generated by Django 5.1.3 on 2024-11-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_delete_certification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='consumable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
