# Generated by Django 5.1.3 on 2024-11-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_location',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
