# Generated by Django 5.1.3 on 2024-11-20 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_well'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=500)),
                ('tool_used', models.BooleanField(default=False, null=True)),
                ('tool_hours', models.FloatField(blank=True, null=True)),
                ('tool_distance', models.FloatField(blank=True, null=True)),
                ('tool_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.location')),
                ('well_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.well')),
            ],
        ),
    ]
