# Generated by Django 5.1.3 on 2024-11-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_location_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='data_updates',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='tool_number',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
