# Generated by Django 5.1.3 on 2024-11-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_tool_data_updates_tool_tool_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='data_updates',
            new_name='data_updated',
        ),
    ]
