# Generated by Django 5.1.3 on 2024-11-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_data_updates_tool_data_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='data_updated',
            new_name='date_updated',
        ),
    ]
