# Generated by Django 5.1.3 on 2024-11-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_crew'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='job_title',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
