# Generated by Django 5.1.3 on 2024-11-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_crew_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
