# Generated by Django 5.1.3 on 2024-11-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_crew_date_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('note', models.TextField(max_length=10000)),
                ('note_date', models.DateField(auto_now_add=True)),
                ('note_update', models.DateField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
