# Generated by Django 5.1.3 on 2024-11-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('lift_frame', models.BooleanField(default=False)),
                ('mpd_manifold_building', models.BooleanField(default=False)),
                ('rcd_housing', models.BooleanField(default=False)),
                ('pipework', models.BooleanField(default=False)),
                ('mpd_supervisor', models.IntegerField(default=2)),
                ('mpd_operator', models.IntegerField(default=2)),
            ],
        ),
    ]
