# Generated by Django 5.1.3 on 2024-11-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
