# Generated by Django 5.1.3 on 2024-11-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_day_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='lift_frame',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='day',
            name='mpd_manifold_building',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='pipework',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='day',
            name='rcd_housing',
            field=models.IntegerField(default=0),
        ),
    ]
