# Generated by Django 5.1.3 on 2024-11-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_remove_day_name_day_well_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
