# Generated by Django 5.1.3 on 2024-11-22 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_certificate_alter_tool_tool_used_crew_certificates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='certificates',
        ),
        migrations.AddField(
            model_name='certificate',
            name='crew_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.crew'),
        ),
    ]
