# Generated by Django 5.1.3 on 2024-11-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_remove_crew_certificates_certificate_crew_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='crew_member',
        ),
    ]
