# Generated by Django 5.1.3 on 2024-11-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_crew_certificates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='certificates',
        ),
        migrations.AddField(
            model_name='crew',
            name='bst',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crew',
            name='iwcf',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
