# Generated by Django 5.1.3 on 2024-11-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_remove_crew_certificates_crew_bst_crew_iwcf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crew',
            old_name='bst',
            new_name='BST',
        ),
        migrations.RenameField(
            model_name='crew',
            old_name='iwcf',
            new_name='IWCF',
        ),
    ]
