# Generated by Django 5.1.3 on 2024-11-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_rename_bst_crew_bst_rename_iwcf_crew_iwcf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
