# Generated by Django 5.1.3 on 2024-11-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_sum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sum',
        ),
        migrations.AddField(
            model_name='crew',
            name='H2S',
            field=models.BooleanField(default=False),
        ),
    ]
