# Generated by Django 5.1.3 on 2024-11-26 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_delete_sum_crew_h2s'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CriticalSpare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('detail', models.CharField(max_length=500)),
                ('quantity_in_unit', models.IntegerField(default=0)),
                ('quantity_on_location', models.IntegerField(default=0)),
                ('vendor', models.CharField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(max_length=10000)),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.category')),
            ],
        ),
    ]
