# Generated by Django 5.1.3 on 2024-11-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_spare_delete_criticalspare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='notes',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
