# Generated by Django 5.1.3 on 2024-11-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_alter_spare_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='date_bst',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='crew',
            name='date_h2s',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='crew',
            name='date_iwcf',
            field=models.DateField(auto_now=True),
        ),
    ]
