# Generated by Django 5.1.3 on 2024-11-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_crew_date_bst_crew_date_h2s_crew_date_iwcf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='date_bst',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='crew',
            name='date_h2s',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='crew',
            name='date_iwcf',
            field=models.DateField(),
        ),
    ]
