# Generated by Django 5.1.3 on 2024-11-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_crew_bst_expires_crew_h2s_expires_crew_iwcf_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='bst_expires',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='crew',
            name='h2s_expires',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='crew',
            name='iwcf_expires',
            field=models.DateField(),
        ),
    ]
