# Generated by Django 5.1.3 on 2024-11-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_alter_crew_bst_expires_alter_crew_h2s_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='notes',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
