# Generated by Django 5.1.3 on 2024-11-27 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_alter_spare_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpareLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_location_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='spare',
            name='spare_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.sparelocation'),
        ),
    ]
