# Generated by Django 5.1.3 on 2024-11-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_sparelocation_spare_spare_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='today',
            field=models.DateField(auto_now=True),
        ),
    ]
