# Generated by Django 5.1.3 on 2024-11-29 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_crew_on_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation_date', models.DateField()),
                ('shift', models.CharField(blank=True, max_length=20, null=True)),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.crew')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.location')),
            ],
        ),
    ]
