# Generated by Django 5.1.3 on 2024-11-29 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RcdTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_section', models.CharField(max_length=50)),
                ('run_number', models.IntegerField(default=0)),
                ('rcd_number', models.CharField(max_length=50)),
                ('bearing_number', models.CharField(max_length=50)),
                ('sealing_element', models.CharField(max_length=50)),
                ('total_installed_time', models.FloatField(default=0)),
                ('total_rotating_time', models.FloatField(default=0)),
                ('max_rpm', models.IntegerField(default=0)),
                ('total_stripped_length', models.IntegerField(default=0)),
                ('max_connection_surface_back_pressure', models.IntegerField(default=0)),
                ('max_drilling_surface_back_pressure', models.IntegerField(default=0)),
                ('max_stripping_surface_back_pressure', models.IntegerField(default=0)),
                ('average_flow_line_temp', models.IntegerField(default=0)),
                ('max_flow_line_temp', models.IntegerField(default=0)),
                ('mud_system', models.CharField(max_length=50)),
                ('mud_weight', models.FloatField(default=0)),
                ('sealing_element_failure', models.BooleanField(default=False)),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project')),
                ('well_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.well')),
            ],
        ),
    ]
