# Generated by Django 5.1.3 on 2024-11-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_rcdtracker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RcdTracker',
            new_name='Tracker',
        ),
    ]
