# Generated by Django 5.1.3 on 2024-11-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_rename_rcdtracker_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='average_flow_line_temp',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='max_flow_line_temp',
            field=models.FloatField(default=0),
        ),
    ]
