# Generated by Django 5.1.3 on 2024-11-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_alter_tracker_average_flow_line_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='mpd_manifold_building',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='day',
            name='pipework',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='day',
            name='rcd_housing',
            field=models.IntegerField(default=1),
        ),
    ]
