# Generated by Django 5.1.3 on 2024-12-03 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0043_alter_day_mpd_manifold_building_alter_day_pipework_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.crew')),
            ],
        ),
    ]
