# Generated by Django 5.1.3 on 2024-12-04 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0044_herc'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hole_diameter', models.FloatField(default=0)),
                ('hole_depth', models.FloatField(default=0)),
                ('bearing_number', models.CharField(max_length=50)),
                ('total_length_stripped', models.FloatField(default=0)),
                ('total_rotating_hours', models.FloatField(default=0)),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project')),
                ('well_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.well')),
            ],
        ),
    ]
