# Generated by Django 5.1.3 on 2024-12-05 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_dailyreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField()),
                ('invoice_amount', models.FloatField(default=0)),
                ('invoice_reason', models.CharField(blank=True, max_length=5000, null=True)),
                ('invoice_paid', models.BooleanField(default=False)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('well_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.well')),
            ],
        ),
    ]
