# Generated by Django 5.1.3 on 2024-12-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0046_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='average_flow_line_temp',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='bearing_number',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='hole_section',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='max_connection_surface_back_pressure',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='max_drilling_surface_back_pressure',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='max_flow_line_temp',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='max_rpm',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='max_stripping_surface_back_pressure',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='mud_system',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='mud_weight',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='rcd_number',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='run_number',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='sealing_element',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='sealing_element_failure',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='total_installed_time',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='total_rotating_time',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='total_stripped_length',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='well_name',
        ),
        migrations.AddField(
            model_name='tracker',
            name='drilledLengthRotating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
