# Generated by Django 5.1.3 on 2024-12-09 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0047_remove_tracker_average_flow_line_temp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='bearing_number',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='hole_section',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='rcd_number',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='run_number',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='sealing_element',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='well_name',
        ),
    ]
