# Generated by Django 5.1.3 on 2024-12-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0047_remove_tracker_average_flow_line_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='drilledLengthSliding',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='drilledLengthTotal',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
