# Generated by Django 5.1.3 on 2024-12-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0048_remove_tracker_bearing_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tracker',
        ),
    ]
