# Generated by Django 5.1.3 on 2025-02-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0048_tracker_drilledlengthsliding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='bearing_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='current_operations',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='future_operations',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='operator_weather_delay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='day',
            name='supervisor_weather_delay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='day',
            name='total_distance_stripped',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='total_revolutions',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='total_rotating_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
    ]
