# Generated by Django 5.1.3 on 2025-02-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0049_day_bearing_id_day_current_operations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='test',
            field=models.BooleanField(default=True),
        ),
    ]
