# Generated by Django 5.1.3 on 2025-02-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0050_day_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'verbose_name': 'Daily Reports'},
        ),
        migrations.RemoveField(
            model_name='day',
            name='test',
        ),
    ]
