# Generated by Django 5.1.3 on 2025-02-17 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0051_alter_day_options_remove_day_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={},
        ),
    ]
