# Generated by Django 5.1.3 on 2025-02-17 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0053_tool_tool_revolutions_delete_dailyreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReadinessAssessmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pra_category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectReadinessAssessmentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pra_section_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectReadinessAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_decsription', models.TextField(max_length=10000)),
                ('fin_involved', models.BooleanField(default=False)),
                ('eng_involved', models.BooleanField(default=False)),
                ('ops_involved', models.BooleanField(default=False)),
                ('tec_involved', models.BooleanField(default=False)),
                ('hse_involved', models.BooleanField(default=False)),
                ('sal_involved', models.BooleanField(default=False)),
                ('pnc_involved', models.BooleanField(default=False)),
                ('sup_involved', models.BooleanField(default=False)),
                ('tra_involved', models.BooleanField(default=False)),
                ('qty_involved', models.BooleanField(default=False)),
                ('log_involved', models.BooleanField(default=False)),
                ('fac_involved', models.BooleanField(default=False)),
                ('man_involved', models.BooleanField(default=False)),
                ('task_started', models.BooleanField(default=False)),
                ('low_priority', models.BooleanField(default=True)),
                ('due_date', models.DateField()),
                ('assigned_to', models.CharField(max_length=100)),
                ('date_updated', models.DateField(auto_now_add=True)),
                ('comments', models.TextField(max_length=100000)),
                ('pra_category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pra_category', to='project.projectreadinessassessmentcategory')),
                ('pra_section_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pra_section', to='project.projectreadinessassessmentsection')),
            ],
        ),
    ]
