# Generated by Django 5.1.3 on 2025-02-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0054_projectreadinessassessmentcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='day_due',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
