# Generated by Django 5.1.3 on 2025-02-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0057_alter_note_day_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_paid',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_reason',
        ),
        migrations.AddField(
            model_name='invoice',
            name='engineering',
            field=models.FloatField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='equipment',
            field=models.FloatField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='herc',
            field=models.FloatField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='personnel',
            field=models.FloatField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='project_management',
            field=models.FloatField(default=1, max_length=9),
            preserve_default=False,
        ),
    ]
