# Generated by Django 5.1.3 on 2025-02-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0058_remove_invoice_invoice_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='project_management',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
