# Generated by Django 5.1.3 on 2025-02-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0059_alter_invoice_project_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='engineering',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='equipment',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='herc',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='personnel',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
