# Generated by Django 5.1.3 on 2025-02-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0060_alter_invoice_engineering_alter_invoice_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(unique=True),
        ),
    ]
