# Generated by Django 5.1.3 on 2025-02-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0062_alter_invoice_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='engineering',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='equipment',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='herc',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='personnel',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='project_management',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
