# Generated by Django 5.1.3 on 2025-02-22 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0065_day_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpd_supervisor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mpd_operator', models.DecimalField(decimal_places=2, max_digits=6)),
                ('manifold', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rcd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pipe_work', models.DecimalField(decimal_places=2, max_digits=6)),
                ('uplift', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project')),
                ('well_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.well')),
            ],
        ),
    ]
