# Generated by Django 5.1.3 on 2025-02-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0066_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='manifold',
            new_name='manifold_operational',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='pipe_work',
            new_name='manifold_standby',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='rcd',
            new_name='pipe_work_operational',
        ),
        migrations.AddField(
            model_name='rate',
            name='pipe_work_standby',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='rcd_operational',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='rcd_standby',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
