# Generated by Django 5.1.3 on 2025-02-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0068_day_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='well_section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
