# Generated by Django 5.1.3 on 2025-02-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0070_alter_day_options_alter_tool_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='tool_in_use',
            field=models.BooleanField(default=False),
        ),
    ]
