# Generated by Django 5.1.3 on 2025-03-05 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0071_tool_tool_in_use'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ('-tool_in_use', 'tool_used', '-tool_location')},
        ),
        migrations.RemoveField(
            model_name='day',
            name='rate',
        ),
    ]
