# Generated by Django 5.1.3 on 2025-03-05 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0073_well_discount_well_manifold_operational_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='well',
            name='manifold_operational',
        ),
        migrations.RemoveField(
            model_name='well',
            name='manifold_standby',
        ),
        migrations.RemoveField(
            model_name='well',
            name='pipe_work_operational',
        ),
        migrations.RemoveField(
            model_name='well',
            name='pipe_work_standby',
        ),
        migrations.RemoveField(
            model_name='well',
            name='rcd_operational',
        ),
        migrations.RemoveField(
            model_name='well',
            name='rcd_standby',
        ),
        migrations.RemoveField(
            model_name='well',
            name='uplift',
        ),
        migrations.AddField(
            model_name='day',
            name='rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.rate'),
        ),
    ]
