# Generated by Django 5.1.3 on 2025-04-15 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0074_remove_well_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={},
        ),
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_od', models.CharField(max_length=500)),
                ('pipe_sn', models.CharField(max_length=500)),
                ('pipe_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.location')),
            ],
        ),
    ]
